services:
  - type: web
    name: GlowCart-Ecommerce
    env: python
    region: oregon
    branch: main
    buildCommand: cd main_project && pip install -r requirements.txt && python manage.py collectstatic --noinput
    releaseCommand: cd main_project && python manage.py migrate --noinput
    startCommand: cd main_project && gunicorn ecommerce_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: USE_SQLITE
        value: "True"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*"
      - key: DJANGO_SECRET_KEY
        value: "glowcart-secret-key-prod-12345"
      - key: DEFAULT_FROM_EMAIL
        value: "noreply@glowcart.com"
