# Generated by Django 6.0.2 on 2026-03-31 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_question', models.CharField(choices=[('childhood_street', 'What was the name of the street you grew up on?'), ('first_pet', 'What was the name of your first pet?'), ('first_boss', 'What was the first name of your first boss?'), ('family_birth_city', 'In what city was your oldest sibling born?'), ('first_car_model', 'What was the model of your first car?'), ('favorite_teacher', 'What was the last name of your favorite teacher?'), ('childhood_best_friend', 'What was the first name of your childhood best friend?'), ('first_job_title', 'What was your first job title?'), ('first_concert', 'What was the first concert you attended?')], max_length=50)),
                ('security_answer', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
