# Generated by Django 6.0.2 on 2026-03-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home & Garden'), ('beauty', 'Beauty & Personal Care'), ('sports', 'Sports & Outdoors'), ('toys', 'Toys & Games'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('open_box', 'Open Box'), ('used_excellent', 'Used - Excellent'), ('used_good', 'Used - Good'), ('used_fair', 'Used - Fair')], default='new', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='Enter key technical specs', null=True),
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
